version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"  # Exemplo, pode remover se não quiser expor
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/soccer_data
      - MINIO_URL=http://minio:9000
    networks:
      - dev_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: soccer_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - dev_network

volumes:
  postgres_data:

networks:
  dev_network:
